--DDL

CREATE DATABASE Exercicio_1_4_Tarde

CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20)
);

CREATE TABLE Album
(
 	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	NomeArtista VARCHAR(20) NOT NULL,
	QuantidadeMinutos VARCHAR(20) NOT NULL,
	Lancamento VARCHAR(20)	NOT NULL,
	Estilo VARCHAR(20) NOT NULL,
	Titulo VARCHAR(20) NOT NULL,
	Localizacao VARCHAR(20) NOT NULL,
	ATIVO BIT NOT NULL
);

CREATE TABLE Musica
(
	IdMusica INT PRIMARY KEY IDENTITY,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	TituloMusica VARCHAR(20) NOT NULL
);

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	IdMusica INT FOREIGN KEY REFERENCES Musica(IdMusica),
	NomeEstilo VARCHAR(20) NOT NULL
);

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) UNIQUE NOT NULL,
	Senha VARCHAR(20) NOT NULL,
	NivelPermissao BIT NOT NULL
);

SELECT*FROM Artista
SELECT*FROM Album
SELECT*FROM Musica
SELECT*FROM Estilo
SELECT*FROM Usuario
