--DDL - CRIAR BANCOS E TABELA

CREATE DATABASE Exercicio_1_1;

--USAR O BANCO CRIADO
USE Exercicio_1_1;

--CRIAR TABELAS
CREATE TABLE Pessoa
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	NomePessoa VARCHAR(20) NOT NULL,
	Idade INT NOT NULL,
	Cnh CHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Numero VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Email
(
		IdEmail INT PRIMARY KEY IDENTITY,
		IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
		Endereco VARCHAR(30) NOT NULL UNIQUE
);

SELECT*FROM Pessoa
SELECT*FROM Telefone
SELECT*FROM Email
