--DDL

CREATE DATABASE Exercicio_1_2_TARDE;

USE Exercicio_1_2_TARDE;

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeEmpresa VARCHAR(20) NOT NULL
);

CREATE TABLE Marca 
(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(20) NOT NULL
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	NumeroChassi VARCHAR(17) UNIQUE NOT NULL
);

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	CPF VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca),
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo),
	Placa VARCHAR(7) UNIQUE NOT NULL
);

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo),
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	Preco FLOAT NOT NULL
);

SELECT * FROM Empresa
SELECT * FROM Marca
SELECT * FROM Modelo
SELECT * FROM Cliente
SELECT * FROM Veiculo
SELECT * FROM Aluguel