--DDL

CREATE DATABASE Exercicio_1_3;

USE Exercicio_1_3;

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(20) NOT NULL
);

CREATE TABLE Dono	
(
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(20) NOT NULL
);

CREATE TABLE TiposPets
(
	IdTiposPets INT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Raca VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	NomeVeterinario VARCHAR(20) NOT NULL
);

CREATE TABLE Pets
(
	IdPets INT PRIMARY KEY IDENTITY,
	IdTiposPets INT FOREIGN KEY REFERENCES TiposPets(IdTiposPets),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	Nome VARCHAR(20) NOT NULL,
	DataNascimento VARCHAR(20) NOT NULL
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPets INT FOREIGN KEY REFERENCES Pets(IdPets),
	DataAtendimento VARCHAR(20) NOT NULL
);

SELECT * FROM Clinica
SELECT * FROM Dono
SELECT * FROM TiposPets
SELECT * FROM Raca
SELECT * FROM Veterinario
SELECT * FROM Pets
SELECT * FROM Atendimento

